In [20]:
# Load libraries

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import accuracy_score #Import scikit-learn metrics module for accuracy calculation
from sklearn import tree
#To create a confusion matrix
from sklearn.metrics import confusion_matrix

In [7]:
pima = pd.read_csv("diabetes.csv")

In [8]:
pima.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [9]:
pima.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
print("Dataset Lenght:: ", len(pima))
print("Dataset Shape:: ", pima.shape)

Dataset Lenght::  768
Dataset Shape::  (768, 9)

In [11]:
pima.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [39]:
pima[pima.Insulin == 0].count()

Pregnancies                 374
Glucose                     374
BloodPressure               374
SkinThickness               374
Insulin                     374
BMI                         374
DiabetesPedigreeFunction    374
Age                         374
Outcome                     374
dtype: int64

In [ ]:
#BMI Insulin Age DiabetesPedigreeFunction BloodPressure Glucose

In [52]:
pima[["Outcome", "SkinThickness"]].groupby(["SkinThickness"]).describe()

              Outcome
                count      mean       std  min   25%  50%   75%  max
SkinThickness
0               227.0  0.387665  0.488294  0.0  0.00  0.0  1.00  1.0
7                 2.0  0.500000  0.707107  0.0  0.25  0.5  0.75  1.0
8                 2.0  0.000000  0.000000  0.0  0.00  0.0  0.00  0.0
10                5.0  0.000000  0.000000  0.0  0.00  0.0  0.00  0.0
11                6.0  0.000000  0.000000  0.0  0.00  0.0  0.00  0.0
12                7.0  0.142857  0.377964  0.0  0.00  0.0  0.00  1.0
13               11.0  0.090909  0.301511  0.0  0.00  0.0  0.00  1.0
14                6.0  0.333333  0.516398  0.0  0.00  0.0  0.75  1.0
15               14.0  0.071429  0.267261  0.0  0.00  0.0  0.00  1.0
16                6.0  0.000000  0.000000  0.0  0.00  0.0  0.00  0.0
17               14.0  0.142857  0.363137  0.0  0.00  0.0  0.00  1.0
18               20.0  0.200000  0.410391  0.0  0.00  0.0  0.00  1.0
19               18.0  0.166667  0.383482  0.0  0.00  0.0  0.00  1.0
20               13.0  0.153846  0.375534  0.0  0.00  0.0  0.00  1.0
21               10.0  0.200000  0.421637  0.0  0.00  0.0  0.00  1.0
22               16.0  0.250000  0.447214  0.0  0.00  0.0  0.25  1.0
23               22.0  0.181818  0.394771  0.0  0.00  0.0  0.00  1.0
24               12.0  0.500000  0.522233  0.0  0.00  0.5  1.00  1.0
25               16.0  0.312500  0.478714  0.0  0.00  0.0  1.00  1.0
26               16.0  0.375000  0.500000  0.0  0.00  0.0  1.00  1.0
27               23.0  0.304348  0.470472  0.0  0.00  0.0  1.00  1.0
28               20.0  0.250000  0.444262  0.0  0.00  0.0  0.25  1.0
29               17.0  0.411765  0.507300  0.0  0.00  0.0  1.00  1.0
30               27.0  0.333333  0.480384  0.0  0.00  0.0  1.00  1.0
31               19.0  0.315789  0.477567  0.0  0.00  0.0  1.00  1.0
32               31.0  0.451613  0.505879  0.0  0.00  0.0  1.00  1.0
33               20.0  0.450000  0.510418  0.0  0.00  0.0  1.00  1.0
34                8.0  0.375000  0.517549  0.0  0.00  0.0  1.00  1.0
35               15.0  0.533333  0.516398  0.0  0.00  1.0  1.00  1.0
36               14.0  0.571429  0.513553  0.0  0.00  1.0  1.00  1.0
37               16.0  0.500000  0.516398  0.0  0.00  0.5  1.00  1.0
38                7.0  0.285714  0.487950  0.0  0.00  0.0  0.50  1.0
39               18.0  0.444444  0.511310  0.0  0.00  0.0  1.00  1.0
40               16.0  0.312500  0.478714  0.0  0.00  0.0  1.00  1.0
41               15.0  0.466667  0.516398  0.0  0.00  0.0  1.00  1.0
42               11.0  0.545455  0.522233  0.0  0.00  1.0  1.00  1.0
43                6.0  0.333333  0.516398  0.0  0.00  0.0  0.75  1.0
44                5.0  0.600000  0.547723  0.0  0.00  1.0  1.00  1.0
45                6.0  0.500000  0.547723  0.0  0.00  0.5  1.00  1.0
46                8.0  0.625000  0.517549  0.0  0.00  1.0  1.00  1.0
47                4.0  0.500000  0.577350  0.0  0.00  0.5  1.00  1.0
48                4.0  0.500000  0.577350  0.0  0.00  0.5  1.00  1.0
49                3.0  1.000000  0.000000  1.0  1.00  1.0  1.00  1.0
50                3.0  0.000000  0.000000  0.0  0.00  0.0  0.00  0.0
51                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
52                2.0  0.000000  0.000000  0.0  0.00  0.0  0.00  0.0
54                2.0  0.000000  0.000000  0.0  0.00  0.0  0.00  0.0
56                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
60                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
63                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
99                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0

In [12]:
#split dataset in features and target variable

feature_cols = ["Pregnancies", 'Glucose', 'BloodPressure', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
X = pima[feature_cols] #features

In [139]:
X

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,0,33.6,0.627,50
1,1,85,66,0,26.6,0.351,31
2,8,183,64,0,23.3,0.672,32
3,1,89,66,94,28.1,0.167,21
4,0,137,40,168,43.1,2.288,33
5,5,116,74,0,25.6,0.201,30
6,3,78,50,88,31.0,0.248,26
7,10,115,0,0,35.3,0.134,29
8,2,197,70,543,30.5,0.158,53
9,8,125,96,0,0.0,0.232,54
10,4,110,92,0,37.6,0.191,30
11,10,168,74,0,38.0,0.537,34
12,10,139,80,0,27.1,1.441,57
13,1,189,60,846,30.1,0.398,59
14,5,166,72,175,25.8,0.587,51
15,7,100,0,0,30.0,0.484,32
16,0,118,84,230,45.8,0.551,31
17,7,107,74,0,29.6,0.254,31
18,1,103,30,83,43.3,0.183,33
19,1,115,70,96,34.6,0.529,32
20,3,126,88,235,39.3,0.704,27
21,8,99,84,0,35.4,0.388,50
22,7,196,90,0,39.8,0.451,41
23,9,119,80,0,29.0,0.263,29
24,11,143,94,146,36.6,0.254,51
25,10,125,70,115,31.1,0.205,41
26,7,147,76,0,39.4,0.257,43
27,1,97,66,140,23.2,0.487,22
28,13,145,82,110,22.2,0.245,57
29,5,117,92,0,34.1,0.337,38
...,...,...,...,...,...,...,...
738,2,99,60,160,36.6,0.453,21
739,1,102,74,0,39.5,0.293,42
740,11,120,80,150,42.3,0.785,48
741,3,102,44,94,30.8,0.400,26
742,1,109,58,116,28.5,0.219,22
743,9,140,94,0,32.7,0.734,45
744,13,153,88,140,40.6,1.174,39
745,12,100,84,105,30.0,0.488,46
746,1,147,94,0,49.3,0.358,27
747,1,81,74,57,46.3,1.096,32
748,3,187,70,200,36.4,0.408,36
749,6,162,62,0,24.3,0.178,50
750,4,136,70,0,31.2,1.182,22
751,1,121,78,74,39.0,0.261,28
752,3,108,62,0,26.0,0.223,25
753,0,181,88,510,43.3,0.222,26
754,8,154,78,0,32.4,0.443,45
755,1,128,88,110,36.5,1.057,37
756,7,137,90,0,32.0,0.391,39
757,0,123,72,0,36.3,0.258,52
758,1,106,76,0,37.5,0.197,26
759,6,190,92,0,35.5,0.278,66
760,2,88,58,16,28.4,0.766,22
761,9,170,74,0,44.0,0.403,43
762,9,89,62,0,22.5,0.142,33
763,10,101,76,180,32.9,0.171,63
764,2,122,70,0,36.8,0.340,27
765,5,121,72,112,26.2,0.245,30
766,1,126,60,0,30.1,0.349,47
767,1,93,70,0,30.4,0.315,23

In [13]:
y = pima["Outcome"] #target variables

In [26]:
pima.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [14]:
pima.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [15]:
print("Dataset:: ")
pima.head()

Dataset::

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [16]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100) # 70% training and 30% test
# The parameter test_size is given value 0.3; it means test sets will be 30% of whole dataset  
# & training dataset’s size will be 70% of the entire dataset. random_state variable is a pseudo-random number 
# generator state used for random sampling. If you want to replicate our results, then use the same value of random_state.

In [17]:
## Fitting the Decision regression tree to the dataset
clf_gini = DecisionTreeClassifier(criterion="gini", random_state = 100, max_depth = 3, min_samples_leaf = 5)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [18]:
y_pred = clf_gini.predict(X_test)
y_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

**Classifying new Observations**

In [21]:
c = confusion_matrix(y_test, y_pred)
c

array([[140,  10],
       [ 54,  27]], dtype=int64)

**Accuracy**

In [22]:
#Overall Accuracy

(c[0,0]+c[1,1])/np.sum(c)*100

72.2943722943723

**Model 2**

In [30]:
pima.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [53]:
#split dataset in features and target variable

feature_cols1 = ["Pregnancies", 'Glucose', 'BloodPressure', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'SkinThickness']
X1 = pima[feature_cols] #features

In [54]:
y1 = pima["Outcome"] #target variables

In [55]:
# Split dataset into training set and test set
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3, random_state=100)

In [56]:
## Fitting the Decision regression tree to the dataset
clf = DecisionTreeClassifier(criterion="gini", random_state = 100, max_depth = 3, min_samples_leaf = 5)
clf.fit(X1_train, y1_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [57]:
y1_pred = clf.predict(X1_test)
y1_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [60]:
c1 = confusion_matrix(y1_test, y1_pred)
c1

array([[140,  10],
       [ 54,  27]], dtype=int64)

In [61]:
(c1[0,0]+c1[1,1])/np.sum(c1)*100

72.2943722943723

**Model 3**

In [85]:
pima[['Outcome','Glucose','BloodPressure','BMI','DiabetesPedigreeFunction']].groupby(['Glucose','BloodPressure','BMI','DiabetesPedigreeFunction']).describe()

                                                    Outcome                \
                                                      count mean std  min
Glucose BloodPressure BMI  DiabetesPedigreeFunction
0       48            24.7 0.140                        1.0  0.0 NaN  0.0
        68            32.0 0.389                        1.0  0.0 NaN  0.0
                      39.0 0.727                        1.0  1.0 NaN  1.0
        74            27.7 0.299                        1.0  0.0 NaN  0.0
        80            41.0 0.346                        1.0  1.0 NaN  1.0
44      62            25.0 0.587                        1.0  0.0 NaN  0.0
56      56            24.2 0.332                        1.0  0.0 NaN  0.0
57      60            21.7 0.735                        1.0  0.0 NaN  0.0
        80            32.8 0.096                        1.0  0.0 NaN  0.0
61      82            34.4 0.243                        1.0  0.0 NaN  0.0
62      78            32.6 0.391                        1.0  0.0 NaN  0.0
65      72            32.0 0.600                        1.0  0.0 NaN  0.0
67      76            45.3 0.194                        1.0  0.0 NaN  0.0
68      62            20.1 0.257                        1.0  0.0 NaN  0.0
        70            25.0 0.187                        1.0  0.0 NaN  0.0
        106           35.5 0.285                        1.0  0.0 NaN  0.0
71      48            20.4 0.323                        1.0  0.0 NaN  0.0
        62            21.8 0.416                        1.0  0.0 NaN  0.0
        70            28.0 0.586                        1.0  0.0 NaN  0.0
        78            33.2 0.422                        1.0  0.0 NaN  0.0
72      78            31.6 0.280                        1.0  0.0 NaN  0.0
73      0             21.1 0.342                        1.0  0.0 NaN  0.0
        50            23.0 0.248                        1.0  0.0 NaN  0.0
        60            26.8 0.268                        1.0  0.0 NaN  0.0
74      0             0.0  0.102                        1.0  0.0 NaN  0.0
        52            27.8 0.269                        1.0  0.0 NaN  0.0
        68            29.7 0.293                        1.0  0.0 NaN  0.0
        70            35.3 0.705                        1.0  0.0 NaN  0.0
75      64            29.7 0.370                        1.0  0.0 NaN  0.0
        82            33.3 0.263                        1.0  0.0 NaN  0.0
...                                                     ...  ...  ..  ...
184     85            30.0 1.213                        1.0  1.0 NaN  1.0
186     90            34.5 0.423                        1.0  1.0 NaN  1.0
187     50            33.9 0.826                        1.0  1.0 NaN  1.0
        68            37.7 0.254                        1.0  1.0 NaN  1.0
        70            36.4 0.408                        1.0  1.0 NaN  1.0
        76            43.6 1.034                        1.0  1.0 NaN  1.0
188     78            47.9 0.137                        1.0  1.0 NaN  1.0
        82            32.0 0.682                        1.0  1.0 NaN  1.0
189     60            30.1 0.398                        1.0  1.0 NaN  1.0
        64            31.2 0.583                        1.0  1.0 NaN  1.0
        104           34.3 0.435                        1.0  1.0 NaN  1.0
        110           28.5 0.680                        1.0  0.0 NaN  0.0
190     92            35.5 0.278                        1.0  1.0 NaN  1.0
191     68            30.9 0.299                        1.0  0.0 NaN  0.0
193     50            25.9 0.655                        1.0  0.0 NaN  0.0
        70            34.9 0.241                        1.0  1.0 NaN  1.0
194     68            35.9 0.745                        1.0  1.0 NaN  1.0
        78            23.5 0.129                        1.0  1.0 NaN  1.0
        80            26.1 0.551                        1.0  0.0 NaN  0.0
195     70            25.1 0.163                        1.0  1.0 NaN  1.0
                      30.9 0.328                        1.0  1.0 NaN  1.0
196     76            36.5 0.875                        1.0  1.0 NaN  1.0
                      37.5 0.605                        1.0  1.0 NaN  1.0
        90            39.8 0.451                        1.0  1.0 NaN  1.0
197     70            30.5 0.158                        1.0  1.0 NaN  1.0
                      34.7 0.575                        1.0  1.0 NaN  1.0
                      36.7 2.329                        1.0  0.0 NaN  0.0
        74            25.9 1.191                        1.0  1.0 NaN  1.0
198     66            41.3 0.502                        1.0  1.0 NaN  1.0
199     76            42.9 1.394                        1.0  1.0 NaN  1.0


                                                     25%  50%  75%  max
Glucose BloodPressure BMI  DiabetesPedigreeFunction
0       48            24.7 0.140                     0.0  0.0  0.0  0.0
        68            32.0 0.389                     0.0  0.0  0.0  0.0
                      39.0 0.727                     1.0  1.0  1.0  1.0
        74            27.7 0.299                     0.0  0.0  0.0  0.0
        80            41.0 0.346                     1.0  1.0  1.0  1.0
44      62            25.0 0.587                     0.0  0.0  0.0  0.0
56      56            24.2 0.332                     0.0  0.0  0.0  0.0
57      60            21.7 0.735                     0.0  0.0  0.0  0.0
        80            32.8 0.096                     0.0  0.0  0.0  0.0
61      82            34.4 0.243                     0.0  0.0  0.0  0.0
62      78            32.6 0.391                     0.0  0.0  0.0  0.0
65      72            32.0 0.600                     0.0  0.0  0.0  0.0
67      76            45.3 0.194                     0.0  0.0  0.0  0.0
68      62            20.1 0.257                     0.0  0.0  0.0  0.0
        70            25.0 0.187                     0.0  0.0  0.0  0.0
        106           35.5 0.285                     0.0  0.0  0.0  0.0
71      48            20.4 0.323                     0.0  0.0  0.0  0.0
        62            21.8 0.416                     0.0  0.0  0.0  0.0
        70            28.0 0.586                     0.0  0.0  0.0  0.0
        78            33.2 0.422                     0.0  0.0  0.0  0.0
72      78            31.6 0.280                     0.0  0.0  0.0  0.0
73      0             21.1 0.342                     0.0  0.0  0.0  0.0
        50            23.0 0.248                     0.0  0.0  0.0  0.0
        60            26.8 0.268                     0.0  0.0  0.0  0.0
74      0             0.0  0.102                     0.0  0.0  0.0  0.0
        52            27.8 0.269                     0.0  0.0  0.0  0.0
        68            29.7 0.293                     0.0  0.0  0.0  0.0
        70            35.3 0.705                     0.0  0.0  0.0  0.0
75      64            29.7 0.370                     0.0  0.0  0.0  0.0
        82            33.3 0.263                     0.0  0.0  0.0  0.0
...                                                  ...  ...  ...  ...
184     85            30.0 1.213                     1.0  1.0  1.0  1.0
186     90            34.5 0.423                     1.0  1.0  1.0  1.0
187     50            33.9 0.826                     1.0  1.0  1.0  1.0
        68            37.7 0.254                     1.0  1.0  1.0  1.0
        70            36.4 0.408                     1.0  1.0  1.0  1.0
        76            43.6 1.034                     1.0  1.0  1.0  1.0
188     78            47.9 0.137                     1.0  1.0  1.0  1.0
        82            32.0 0.682                     1.0  1.0  1.0  1.0
189     60            30.1 0.398                     1.0  1.0  1.0  1.0
        64            31.2 0.583                     1.0  1.0  1.0  1.0
        104           34.3 0.435                     1.0  1.0  1.0  1.0
        110           28.5 0.680                     0.0  0.0  0.0  0.0
190     92            35.5 0.278                     1.0  1.0  1.0  1.0
191     68            30.9 0.299                     0.0  0.0  0.0  0.0
193     50            25.9 0.655                     0.0  0.0  0.0  0.0
        70            34.9 0.241                     1.0  1.0  1.0  1.0
194     68            35.9 0.745                     1.0  1.0  1.0  1.0
        78            23.5 0.129                     1.0  1.0  1.0  1.0
        80            26.1 0.551                     0.0  0.0  0.0  0.0
195     70            25.1 0.163                     1.0  1.0  1.0  1.0
                      30.9 0.328                     1.0  1.0  1.0  1.0
196     76            36.5 0.875                     1.0  1.0  1.0  1.0
                      37.5 0.605                     1.0  1.0  1.0  1.0
        90            39.8 0.451                     1.0  1.0  1.0  1.0
197     70            30.5 0.158                     1.0  1.0  1.0  1.0
                      34.7 0.575                     1.0  1.0  1.0  1.0
                      36.7 2.329                     0.0  0.0  0.0  0.0
        74            25.9 1.191                     1.0  1.0  1.0  1.0
198     66            41.3 0.502                     1.0  1.0  1.0  1.0
199     76            42.9 1.394                     1.0  1.0  1.0  1.0

[768 rows x 8 columns]

In [83]:
#split dataset in features and target variable

# feature_cols2 = ['Glucose','BloodPressure','BMI','DiabetesPedigreeFunction'] # 73.16017316017316
feature_cols2 = ['Glucose','BloodPressure','BMI','DiabetesPedigreeFunction'] 
X2 = pima[feature_cols2] #features

y2 = pima["Outcome"] #target variables

# Split dataset into training set and test set
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3, random_state=100)

## Fitting the Decision regression tree to the dataset
clf2 = DecisionTreeClassifier(criterion="gini", random_state = 100, max_depth = 3, min_samples_leaf = 5)
clf.fit(X2_train, y2_train)

y2_pred = clf.predict(X2_test)
y2_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [84]:
c2 = confusion_matrix(y2_test, y2_pred)
(c2[0,0]+c2[1,1])/np.sum(c2)*100

73.16017316017316

**Model 4**

In [97]:
pima[['Outcome','Glucose','BloodPressure']].groupby(['Glucose','BloodPressure']).describe()

                      Outcome
                        count      mean       std  min   25%  50%   75%  max
Glucose BloodPressure
0       48                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        68                2.0  0.500000  0.707107  0.0  0.25  0.5  0.75  1.0
        74                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        80                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
44      62                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
56      56                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
57      60                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        80                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
61      82                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
62      78                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
65      72                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
67      76                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
68      62                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        70                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        106               1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
71      48                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        62                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        70                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        78                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
72      78                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
73      0                 1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        50                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        60                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
74      0                 1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        52                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        68                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        70                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
75      64                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        82                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
76      60                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
...                       ...       ...       ...  ...   ...  ...   ...  ...
183     64                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        94                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
184     78                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        84                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        85                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
186     90                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
187     50                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        68                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        70                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        76                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
188     78                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        82                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
189     60                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        64                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        104               1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        110               1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
190     92                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
191     68                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
193     50                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
        70                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
194     68                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        78                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
        80                1.0  0.000000       NaN  0.0  0.00  0.0  0.00  0.0
195     70                2.0  1.000000  0.000000  1.0  1.00  1.0  1.00  1.0
196     76                2.0  1.000000  0.000000  1.0  1.00  1.0  1.00  1.0
        90                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
197     70                3.0  0.666667  0.577350  0.0  0.50  1.0  1.00  1.0
        74                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
198     66                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0
199     76                1.0  1.000000       NaN  1.0  1.00  1.0  1.00  1.0

[655 rows x 8 columns]

In [98]:
#split dataset in features and target variable

# feature_cols2 = ['Glucose','BloodPressure','BMI','DiabetesPedigreeFunction'] # 73.16017316017316
feature_cols2 = ['Glucose','BloodPressure'] 
X2 = pima[feature_cols2] #features

y2 = pima["Outcome"] #target variables

# Split dataset into training set and test set
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3, random_state=100)

## Fitting the Decision regression tree to the dataset
clf2 = DecisionTreeClassifier(criterion="gini", random_state = 100, max_depth = 3, min_samples_leaf = 5)
clf.fit(X2_train, y2_train)

y2_pred = clf.predict(X2_test)
y2_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [99]:
c2 = confusion_matrix(y2_test, y2_pred)
(c2[0,0]+c2[1,1])/np.sum(c2)*100

73.16017316017316